module.exports = {
  content: ["./*.html", "./src/**/*.css"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b1c1db",
        "secondary-container": "#dae2fd",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#004e60",
        "outline": "#6c797f",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container": "#eceef0",
        "secondary": "#565e74",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001f28",
        "primary": "#00677f",
        "on-secondary-container": "#5c647a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#3f4f65",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#4cd6ff",
        "on-background": "#191c1e",
        "primary-container": "#00d1ff",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#0b1c30",
        "on-surface-variant": "#3c494e",
        "primary-fixed": "#b7eaff",
        "surface-tint": "#00677f",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "tertiary": "#505f76",
        "inverse-primary": "#4cd6ff",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#00566a",
        "on-primary": "#ffffff",
        "background": "#f7f9fb",
        "outline-variant": "#bbc9cf",
        "on-secondary-fixed-variant": "#3f465c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "sm": "12px",
        "xl": "64px",
        "xs": "4px",
        "base": "8px",
        "margin": "32px",
        "md": "24px",
        "lg": "40px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
